### ISSUE TITLE
Backand mapping failed for rubygem-concurrent-ruby

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#100]
Not sure how the-new-hotness tries to map the backends, but this is really surprising:

```
hotness tried to map rubygem-concurrent-ruby to an upstream project, but failed:  "Could not determine backend for http://www.concurrent-ruby.com"
    http://www.concurrent-ruby.com
```

Why it tries some URL, when there is `rubygem-` prefix in package name?

**Comment by jeremycline** [comment]
Thanks for the report, @voxik!

This sounds like #116. I know this was filed earlier, but there's more information on #116 so I'm going to close this one in favor of that one.
