### ISSUE TITLE
Bug 1316528 does not have scratch build attached/linked and See logs and attachments in this bugzilla global name 'os' is not defined

### ISSUE THREAD

**Issue by adelton** [fedora-infra/the-new-hotness#110]
The bug https://bugzilla.redhat.com/show_bug.cgi?id=1316528 was filed for mod_auth_openidc.

In https://bugzilla.redhat.com/show_bug.cgi?id=1316528#c1 it says

```
Patching or scratch build for mod_auth_openidc and version 1.8.7 FAILED.
See for details
```

but it's not clear what should be seen.

In https://bugzilla.redhat.com/show_bug.cgi?id=1316528#c2 it says

```
Rebase helper failed.
See logs and attachments in this bugzilla global name 'os' is not defined
```

which seems like the-new-hotness (or something related) failed, not the builds.

If this is not the correct project to report this sort of errors, please amend https://fedoraproject.org/wiki/Upstream_release_monitoring with some links about the bugzillas being filed.

**Comment by phracek** [comment]
I am setting a machine. I will inform you or I will send a PR.
It takes a time.

**Comment by ralphbean** [comment]
> If this is not the correct project to report this sort of errors

You found the right place!  Like @phracek said, we're working on a new version with a much more robust patch and test mechanism (powered by the rebase-helper tool) but.. we're still working out the kinks.  ;)  Thanks for your patience!

**Comment by phracek** [comment]
I have created a new PR. I did not find a reason yet, why import os is not defined.
On my private OpenStack machine. All work fine. See https://partner-bugzilla.redhat.com/show_bug.cgi?id=1262713

**Comment by phracek** [comment]
As you can see https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/bz.py#L26 import os is defined.

@ralphbean Can you please verify on staging machine if this import is defined?

**Comment by ralphbean** [comment]
Oh, I see.  I mis-applied a hotfix.  The import was missing, but should be fixed now.
