### ISSUE TITLE
Bug 1317494 says "See for details"

### ISSUE THREAD

**Issue by adelton** [fedora-infra/the-new-hotness#113]
This might or might not be related to https://github.com/fedora-infra/the-new-hotness/issues/110.

In https://bugzilla.redhat.com/show_bug.cgi?id=1317494#c1, upstream-release-monitoring@fedoraproject.org says

```
Patching or scratch build for perl-DBD-XBase and version 1.05 FAILED.
See for details
```

It is not clear what should be seen and where.

**Comment by phracek** [comment]
Thanks for info. Yes, texts attached to bugzilla has to be clear. Otherwise users will be confused.
