### ISSUE TITLE
the-new-hotness failed to report the recent youtuble-dl version

### ISSUE THREAD

**Issue by tyll** [fedora-infra/the-new-hotness#122]
Last version in the bug report is 2016.04.06:

https://bugzilla.redhat.com/show_bug.cgi?id=1317502

But anitya already found version 2016.04.13

**Comment by sergiomb2** [comment]
+1 , I just report in https://github.com/fedora-infra/anitya/issues/303 ,  I just found more examples and seems that is more a problem of the-new-hotness that stop to work ... 

https://admin.fedoraproject.org/pkgdb/package/rpms/gammu/
https://admin.fedoraproject.org/pkgdb/package/rpms/python-gammu/
https://admin.fedoraproject.org/pkgdb/package/rpms/wammu/

**Comment by Zlopez** [comment]
This should be fixed, the-new-hotness is now reporting new versions without issue.
