### ISSUE TITLE
hotness tried to map rubygem-turbolinks-source to an upstream project, but failed:  "None"

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#126]
Not sure why this fails:

```
hotness tried to map rubygem-turbolinks-source to an upstream project, but failed:  "None"
    https://github.com/turbolinks/turbolinks-source-gem
```

It should recognize that 'rubygem-' prefixed package should be mapped to rubygems project ...

**Comment by voxik** [comment]
Actually, looking at the mapping, it looks to be mapped properly:

https://release-monitoring.org/project/11320/
https://admin.fedoraproject.org/pkgdb/package/rpms/rubygem-turbolinks-source/anitya

**Comment by pnemade** [comment]
Can you add value of "Homepage" to "GitHub owner/project" and try?

**Comment by voxik** [comment]
> Can you add value of "Homepage" to "GitHub owner/project" and try?

The point is that it should not map to GH project at all. It is rubygem- package, so the RubyGems backend should be used

**Comment by voxik** [comment]
BTW going to change the backend ...

**Comment by Zlopez** [comment]
This issue is too old, so I'm closing this ticket. Feel free to reopen it.
