### ISSUE TITLE
Typo in bugzilla message

### ISSUE THREAD

**Issue by mruprich** [fedora-infra/the-new-hotness#137]
If there is a suggestion to delete a patch, the bugzilla message says: Following patches has been deleted. The correct sentence is: Following patches have been deleted.

**Comment by nforro** [comment]
Hi, thanks for reporting.

This message is actually from rebase-helper, and the typo has already been fixed in PR [#169](https://github.com/rebase-helper/rebase-helper/pull/169).
It should be fixed in the-new-hotness as soon as rebase-helper is updated to 0.8.0 release.

**Comment by jeremycline** [comment]
Since we don't try to rebase patches anymore, I'm going to close this.
