### ISSUE TITLE
Do not report official builds on bugzilla

### ISSUE THREAD

**Issue by pypingou** [fedora-infra/the-new-hotness#14]
Today ppisar was complaining on IRC about the number of emails sent by bugzilla but generated by the-new-hotness.

Before: https://bugzilla.redhat.com/1183577 
After: https://bugzilla.redhat.com/1194256

There are 5 new comments added by the-new-hotness, 4 of which are about the official builds.

While (unlike ppisar) I like the idea of having the results of the scratch-build sent to bugzilla, I think the other 4 comments about the official builds could be dropped.

Proposal:
Before commenting about a non-scratch-build check the comments for a previous message from us, if there is one, do nothing, if there isn't one, add one but then maybe only about rawhide and ignore the other branches.

**Comment by ralphbean** [comment]
Let's just limit it to commenting only about rawhide builds (since bodhi handles the others).

**Comment by tyll** [comment]
On Fri, Feb 20, 2015 at 05:11:47AM -0800, Ralph Bean wrote:
> Let's just limit it to commenting only about rawhide builds (since bodhi handles the others).

It should also be possible to add comments without senden an email.
