### ISSUE TITLE
Consider dropping the dependency on rebase-helper

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/the-new-hotness#145]
We've had several problems integrating with [rebase-helper](https://github.com/rebase-helper/rebase-helper) and currently it does not work at all on Fedora 25 in the development environment. I'm quite new to this project so I don't have the historical context of its addition. I've created a list of features rebase-helper appears to add and some challenges I feel it introduces, which I'm certain can be enriched by someone who _does_ have the historical context and knows what drove its addition to the-new-hotness.

Pros
----
1. Removes patches that have already been applied upstream
2. Detect patches that do not apply cleanly
3. Possibly git-apply does a slightly better job of handling patches
4. Runs rpmdiff, pkgdiff, abipkgdiff, csmock on the old and new packages

Of these, I believe 1. could be easily achieved by unpacking the new source and attempting to apply all the patches (patch will complain that the patch was previously applied), 2. is already possibly via a scratch build of the new version and 3. is a minor benefit (in my opinion). 4. is a bit more work.

Cons
----
1. Has made several API-breaking changes and the latest version is not in EPEL. This makes deploying the-new-hotness in production more difficult since it requires wrangling two packages instead of one.
2. Is currently not functional 😢 

It seems to me that we could get most of what rebase-helper offers while removing a good deal of code and a dependency. The addition of rpmdiff, pkgdiff, abipkgdiff, csmock, etc would require some additional work, but it's really about getting all the RPMs (old and new) sorted out and paired up, I think.

What does everyone else think? Am I missing a big feature here?

**Comment by ignatenkobrain** [comment]
I'm all in for dropping that dependency. It simply doesn't work for ANY of my packages. It drops patches which are not applied in upstream (randomly) and anyway never was able to build new versions..

I think abidiff/etc. is something what you get immediately once you built package in koji and/or can get locally.

**Comment by phracek** [comment]
The basic approach of the rebase-helper and the-new-hotness is to help users with rebases.
Rebase-helper team works on F25 problem. I would not remove rebase-helper from the-new-hotness.
Without rebase-helper it will not work at all in most of the time.
Definitely we have to improve rebase-helper and w/o the-new-hotness we are not able to detect all problems. This is not in our capacity.

What rebase-helper does?
- download the latest sources
- apply the patches
- build SRPM and build RPM
- compare old and new RPM.

The rebase-helper reports ABI diffs, what was changed in RPM package and other stuff.
If we remove it, then we will lost all these information.

**Comment by jeremycline** [comment]
I definitely agree that automating is a good thing, and that running tools against the new package is helpful, but I am of the opinion that it's outside the responsibility of the-new-hotness. I think the-new-hotness should do one thing, and one thing well, which is to file a bugzilla ticket when a new version of a package is available.

When a new update is submitted to Bodhi, a suite of tests is run against it by [Taskatron](https://taskotron.fedoraproject.org/). I think this is the place to run these tests, and the place to display them. We shouldn't re-invent that wheel.

Maybe we shouldn't even be involved in dispatching a scratch build of the new version. How useful it that, really? I'm not sure, but it adds a lot of overhead and work with (IMO) minimal value added.

**Comment by bowlofeggs** [comment]
I think taskotron watches for various events in the infrastructure - one way to get taskotron integration with the-new-hotness might be to file an RFE with taskotron to ask it to respond to the-new-hotness event messages (assuming the-new-hotness emits fedmsgs, but that should be easy to add if it doesn't).

I'm not sure how it would report the results though. I receive taskotron results via IRC (due to my notification settings) for tests it does on my packages after I build them - perhaps that would be good enough?

**Comment by pypingou** [comment]
> Maybe we shouldn't even be involved in dispatching a scratch build of the new version. How useful it that, really? I'm not sure, but it adds a lot of overhead and work with (IMO) minimal value added.

It adds quite some value, the idea of the-new-hotness is this workflow basically:
- detect there is a new release
- inform the packager of a guest estimate of how much work it will be to udpate
  - is the package still building
  - are the patches still relevant (rebase-helper)
- Currently: feed that information to bugzilla
- Ideally: open a pull-request on the pagure instance for src.fp.o and flag the PR based on the result of our checks.

**Comment by pypingou** [comment]
I'm not saying we can't move the testing/checking to taskotron, but then it would be the-new-hotness' duty to learn when a test/check has completed and go back to the PR to flag it accordingly

**Comment by jeremycline** [comment]
Okay, how does this sound?

1. Receive a new release message from Anitya
2. File a bugzilla (in the future create a Pagure issue)
3. Dispatch a scratch build of the package with the version bumped
4. When it's done, follow up on the ticket filed with the results
5. If it succeeded, poke taskotron with our scratch build
6. Taskotron picks up our message and runs whatever checks we want
7. We get the results from Taskotron (fedmsg?)
8. If everything succeeded, attach a patch/create a PR with the simple spec bump.

I've already got 1-4 working on a branch. I'm not sure how much work 5-7 are. 8 is also already functional.

Now, maybe simply bumping the version doesn't work in as many cases, but it's simple and has many fewer opportunities to break.

**Comment by kparal** [comment]
We're talking about running "new koji build" Taskotron checks even for scratch builds. It was just never implemented. I don't know if there are any obstacles in the way, it's best to discuss it in qa-devel list or file a ticket in https://phab.qadevel.cloud.fedoraproject.org/ (URL change coming up). But overall extending our checks to also scratch builds would immediately solve your problem, right?

**Comment by pypingou** [comment]
On Thu, Dec 15, 2016 at 12:27:07PM -0800, Jeremy Cline wrote:
>    Okay, how does this sound?
> 
>     1. Receive a new release message from Anitya
>     2. File a bugzilla (in the future create a Pagure issue)
>     3. Dispatch a scratch build of the package with the version bumped
>     4. When it's done, follow up on the ticket filed with the results
>     5. If it succeeded, poke taskotron with our scratch build
>     6. Taskotron picks up our message and runs whatever checks we want
>     7. We get the results from Taskotron (fedmsg?)
>     8. If everything succeeded, attach a patch/create a PR with the simple
>        spec bump.

Quite good with this issue:
2- creates a notification
4- creates a notification
8- creates a notification

People are complaining they receive too many emails from bugzilla, here they
would get three.
That's why so far the steps 1, 3, 4 and 8 where done before the step 2.
Then came the test results (currently rebase-helper).

**Comment by jeremycline** [comment]
@kparal Yup, that would absolutely solve my problem.

@pypingou Yup, sounds good.

**Comment by jeremycline** [comment]
[It sounds like this will be very easy to implement for Taskotron](https://lists.fedoraproject.org/archives/list/qa-devel@lists.fedoraproject.org/thread/CP77CSQIOQQR7UXBMEXWKN4AJREP7EKF/).

**Comment by jeremycline** [comment]
So I've opened a PR that removes the rebase-helper portion. Reviews and comments are, of course, welcome.

One thing that occurred to me that I didn't really explicitly mention here yet is that I think that ``the-new-hotness`` is not really the place for testing to occur, regardless of whether Taskotron, rebase-helper, Jenkins, etc. runs these tests. It should do one thing, and it should do that one thing (filing issues with the issue tracker in response to upstream releases) well.

``the-new-hotness`` emits fedmsgs, so there's no reason we can't have another service whose one job is to run (or orchestrate the running of) tests with rebase-helper, Taskotron, etc. How does that sound to people?

**Comment by bowlofeggs** [comment]
On Tue, 2017-01-10 at 12:58 -0800, Jeremy Cline wrote:
> the-new-hotness emits fedmsgs, so there's no reason we can't have
> another service whose one job is to run (or orchestrate the running
> of) tests with rebase-helper, Taskotron, etc. How does that sound to
> people?

+1
