### ISSUE TITLE
the-new-hotness appears unable to build packages with ``Suggests``

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/the-new-hotness#156]
The staging deployment of the-new-hotness encountered the following problem:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/hotness/consumers.py", line 338, in _handle_anitya_update
    package, upstream, version, bz)
  File "/usr/lib/python2.7/site-packages/hotness/buildsys.py", line 184, in handle
    ['rpmbuild', '-D', '_sourcedir .', '-D', '_topdir .', '-bs', specfile], cwd=tmp)
  File "/usr/lib/python2.7/site-packages/hotness/buildsys.py", line 121, in run
    raise Exception(message % (' '.join(cmd), p.returncode, out, err))
Exception: cmd:  rpmbuild -D _sourcedir . -D _topdir . -bs /var/tmp/thn-X44tPf/python-librosa.spec
return code:  1
stdout:

stderr:
error: line 45: Unknown tag: Suggests:       python-librosa-doc = 0.5.0rc0-1.el7
```
I don't know exactly what versions of rpm are required to support this, but it'd be nice to figure that out and document/otherwise improve the user experience.

**Comment by pypingou** [comment]
suggests are not supported in el7, we'd need Fedora to have this supported

**Comment by ignatenkobrain** [comment]
I suppose 4.12.

**Comment by mattdm** [comment]
Also "Recommends" — https://bugzilla.redhat.com/show_bug.cgi?id=1535254#c1

**Comment by jeremycline** [comment]
I've filed a [ticket](https://pagure.io/fedora-infrastructure/issue/6637) with infrastructure to move hotness to OpenShift which I'll build on the latest Fedora release.

**Comment by hroncok** [comment]
See also https://github.com/fedora-infra/the-new-hotness/issues/188

**Comment by Zlopez** [comment]
the-new-hotness is now running in OpenShift on where it's currently running on F29. I will update it to F30.I didn't saw any issue like this in long time, so I'm closing this ticket.
