### ISSUE TITLE
Workflow when upstream==fedora maintainer

### ISSUE THREAD

**Issue by xsuchy** [fedora-infra/the-new-hotness#170]
I am upstream maintainer of
  https://github.com/xsuchy/distribution-gpg-keys
at the same time I am Fedora maintainer of this package:
  https://apps.fedoraproject.org/packages/distribution-gpg-keys

When I create upstream release. E.g https://github.com/xsuchy/distribution-gpg-keys/commit/9292d3f8d5ec6ad51899936e58a386e88631dc7a (time is Thu Mar 16 12:10:30 2017 +0100) I immediately create package for Fedora
  https://koji.fedoraproject.org/koji/buildinfo?buildID=869678
The completed time is Thu, 16 Mar 2017 11:16:22 UTC. I.e. three minutes after the upstream release.

Yet I got at 12:11 (UTC) this BZ
   https://bugzilla.redhat.com/show_bug.cgi?id=1433933

In that time there was already tagged build for Fedora.

Note that this happen for other packages where I am upstream maintainer too. And I do not want to disable Anatya notification completely as it is useful for packages where I am not upstream maintainer.
So I would like to address only use case, when Fedora release comes quickly (ie. within an hour) after upstream release. I believe that in this situation the BZ about new release available should not be created.

**Comment by jeremycline** [comment]
Hey @xsuchy, thanks for the report.

It looks like there's a problem with how the-new-hotness is comparing the upstream version to the one in Fedora. It knew 1.10-1.fc27 was in rawhide, but it considers 1.10-1 > 1.10-1.fc27 apparently. I'm working on improving the version comparison support in Anitya and my hope is to eventually turn it into a shared library that hotness can use.

**Comment by Zlopez** [comment]
@xsuchy I would recommend to use monitoring setting in dist-git for the projects, where you are the upstream maintainer and change this to `No-Monitoring`.

This way you shouldn't be notified by the-new-hotness in the future.
