### ISSUE TITLE
Add a debugging mode for the-new-hotness

### ISSUE THREAD

**Issue by jeremycline** [fedora-infra/the-new-hotness#176]
the-new-hotness can be difficult to work with since it depends on Anitya, Koji, and friends to emit fedmsgs. It would be good to add some functionality to the-new-hotness to make developing it easier.

This debug mode would do the following (potentially with some configurability):

* Ignore the fact that a package is already updated in rawhide - sometimes it can be difficult to find a package that has been updated upstream, but isn't yet in rawhide (which is good, but not for us!)

* Ignore the fact that the bugzilla issue already exists - staging uses the partner bugzilla and so do developers.

* Print what would have been filed to stdout rather than creating the bugzilla issue

Additionally, it would be good to set up fedmsg so we can tail the messages hotness publishes. This has been done in the Bodhi development environment, so that's a good place to look for inspiration.

**Comment by Zlopez** [comment]
I was thinking about it and here are some things that could possibly help:
* Do we need to actually connect to any application when debugging? Shouldn't it be better if the-new-hotness just connects to some local simulator running in Vagrant container? This simulator could have configurable response and behaviour. Same could be used for emitting messages.
* There should be documentation how to turn off the above and configure the-new-hotness to actually communicate with system you want.

I know that the fedmsg will be replaced by fedora-messaging soon. So I could start working on some simulator for fedora-messaging. I think this could be helpful for other projects as well.

@jeremycline What are you thinking about this?

**Comment by jeremycline** [comment]
I know a lot more about all this stuff a year later, and things have changed significantly.

the-new-hotness doesn't need to be in the business of making scratch builds, it can open a PR and let the CI handle everything else, so that simplifies things significantly. All you really need is anitya messages and recordings of the mdapi responses so hotness thinks the version is newer/older/equal-to.

With fedora-messaging there's some work to make a simple file format for messages (it's just JSON) and a way to dump/load them easily. Taking that and implementing something similar to VCR where it feeds messages to the consumer callback would be pretty simple, I think.

**Comment by Zlopez** [comment]
VCR like testing library for fedora-messaging seems like a nice feature.

The PR will be much simpler than doing whole scratch build.

For the rest I just need some VCR recordings, that can be used as responses for local work.

Thanks for making it more clear to me.

**Comment by Zlopez** [comment]
There is now [script for replaying fedora messages](https://github.com/fedora-infra/the-new-hotness/blob/2fc7f96e1a5e6f54bfc3819184ba36b662d60cd3/devel/fedora_messaging_replay.py) and the staging environment can be used for more thorough testing. The unit tests are now covering almost 100% of code as well.
The clean architecture allows us to mock/comment parts of the code if needed, so we can remove any system we don't want to test.

I think we can close this issue.
