### ISSUE TITLE
Scratch builds done just sometimes

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#18]
These are latest updates reported by new hotness for my packages:

https://bugzilla.redhat.com/show_bug.cgi?id=1115077
https://bugzilla.redhat.com/show_bug.cgi?id=1118694
https://bugzilla.redhat.com/show_bug.cgi?id=1154598

I am wondering, why the scratch build for rhbz#1118694 was not done.

**Comment by pypingou** [comment]
Without having check the logs, could it be related to Source1?
http://pkgs.fedoraproject.org/cgit/rubygem-gettext_i18n_rails.git/tree/rubygem-gettext_i18n_rails.spec#n14

**Comment by ralphbean** [comment]
> I am wondering, why the scratch build for rhbz#1118694 was not done.

Yeah, hotness failed to even build the SRPM before it could submit it to koji.  It currently doesn't follow up with any information if it fails that early.
