### ISSUE TITLE
A new approach!  Use data from dist-git instead of flags from pkgdb.

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/the-new-hotness#183]
We're [killing pkgdb](https://fedoraproject.org/wiki/Changes/ArbitraryBranching).

Hotness currently depends on pkgdb to query for the monitoring flag to decide what to do about some packages.

We'd like to move that data to a yaml file stored in dist-git (no spec decided for that yet).  We'll need to 1) extract the data from the old pkgdb dump and 2) automate filing pull requests on dist-git repos to re-enable them.

This is a ticket to track modifying hotness to instead query dist-git for its flags instead of pkgdb.

**Comment by ralphbean** [comment]
Changes, changes.

Instead of storing the monitoring information *in dist-git*, we're going to store it at https://pagure.io/dist-git-requests

**Comment by pypingou** [comment]
The idea being that it makes it one place where package maintainers can tweak the settings of their package.

**Comment by Conan-Kudo** [comment]
These better be auto-processed, otherwise it's really going suck compared to how it worked before.

**Comment by pypingou** [comment]
@Conan-Kudo which part of the automation are you thinking about?

**Comment by ralphbean** [comment]
In progress in #185.

**Comment by Conan-Kudo** [comment]
@pypingou Since we no longer have a self-service portal for our package data, the tools we use to modify the data should somehow immediately apply.

**Comment by Zlopez** [comment]
This is already implemented. Closing.
