### ISSUE TITLE
please don't open a new bug if last one is not closed 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/the-new-hotness#187]
I think before hotness had the ability to update the same bug instead open a new one, today for example [1] it opened a second redundant report .

Thanks 

[1]
https://bugzilla.redhat.com/show_bug.cgi?id=1484397
https://bugzilla.redhat.com/show_bug.cgi?id=1508240

**Comment by scfc** [comment]
You filed bug https://bugzilla.redhat.com/show_bug.cgi?id=1484397 yourself; when the original bug is filed by Upstream Release Monitoring, it will append to it further down (cf. for example https://bugzilla.redhat.com/show_bug.cgi?id=1529821).  I think teaching it to understand bugs filed by humans could be very hard.

**Comment by sergiomb2** [comment]
ah oops, so not a bug , thanks closing
