### ISSUE TITLE
File pull requests instead of attaching patches to Bugzilla

### ISSUE THREAD

**Issue by danc86** [fedora-infra/the-new-hotness#189]
Now that we have Pagure over dist-git, it would be really neat if the-new-hotness could file a pull request in Pagure (and then link to it in the Bugzilla comments), rather than attaching the patch to Bugzilla.

We would get all the (future) benefits of pull request testing when that is integrated into Pagure. And it's even easier for the package maintainer to apply -- a single button click, rather than copy pasting stuff to `git am`.

**Comment by bowlofeggs** [comment]
There's a FESCo ticket where something like this is also being proposed: https://pagure.io/fesco/issue/2084

**Comment by Zlopez** [comment]
@bowlofeggs I'm already in contact with ttomecek and we will see how we can work together.

**Comment by bowlofeggs** [comment]
On Fri, 2019-02-08 at 07:38 -0800, Zlopez wrote:
> @bowlofeggs I'm already in contact with ttomecek and we will see how
> we can work together.

Excellent!

**Comment by Zlopez** [comment]
Unfortunately, I can't work on this right now. I need running dist-git for testing and the staging is currently down due to datacenter move and i don't want to use production for testing.

**Comment by szpak** [comment]
@Zlopez When it is planned to bring staging back online (to do not block development of that)?

I was looking to propose that feature to make updates easier/faster available in Fedora, but found this ticket, nice!

**Comment by Zlopez** [comment]
The staging is still work in progress. So I'm not sure when it will be available.

**Comment by Enchufa2** [comment]
Is this still blocked?

**Comment by Zlopez** [comment]
Shouldn't be, I just didn't get time to get back to it.

**Comment by Zlopez** [comment]
This is no longer needed, because Packit now has the [same feature](https://packit.dev/docs/fedora-releases-guide/#pull-from-upstream-job) by watching for hotness messages. So doing this would be duplicate work.
