### ISSUE TITLE
Changelog entry for scratch build is useless

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#19]
It would be nice if the scratch build can contain some more useful entry. You can compare the-new-hotness changelog entry with previous entries for rubygem-jbuilder build for example [1].

Not mentioning that the formatting with quotes etc is suboptimal.

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1154598#c6

**Comment by ralphbean** [comment]
Can you explain more?  Give an example of what you think the changelog should be?

**Comment by voxik** [comment]
Sure, you can compare these two entries:

~~~
* Sun Feb 22 2015 "Fedora Release Monitoring <release-monitoring@fedoraproject.org>" - 2.2.8-1
- "Latest upstream, 2.2.8 for ##1154598 NEW        - jstribny@redhat.com -
  rubygem-jbuilder-2.2.7 is available"

* Tue Oct 14 2014 Josef Stribny <jstribny@redhat.com> - 2.2.2-1
- Update to 2.2.2
~~~

It would be cool if I can just download the srpm, do "fedpkg import" and build. Since the changelog contains "release-monitoring@fedoraproject.org", I will need to change it. The actual descipriton makes no sense to me at all, while the something like "Update to jbuilder 2.2.8." would be quite acceptable.
