### ISSUE TITLE
Normalize version information

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/the-new-hotness#192]
With release-monitoring/anitya#543, anitya supports CRAN. However, the versioning there oftentimes includes a dash. Downstream in Fedora, these dashes are replaced by dashes. As anitya does not want to be in the business of normalizing things for each distro, the-new-hotness needs some way to recognize this disparity so that it does not have trouble checking for out of date packages.

The new backend hasn't been deployed on release-monitoring.org yet, so I'm not sure if this will turn out to be a problem in practice yet.

**Comment by Zlopez** [comment]
The backend was merged in Anitya two years ago and no issue with the dashes were reported. So I thing this could be closed.
