### ISSUE TITLE
Add support for creating github issues for flathub

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#194]
It will be nice if the-new-hotness could create issues about new versions for flathub flatpak packages.

This will be best implemented using [GitHub API v4](https://developer.github.com/v4/).

There needs to be new mapping for Flathub in Anitya. It will be useful if there could be also mapping for dependencies.

**Comment by Zlopez** [comment]
@jeremycline Do you think this could be a nice feature for both Anitya and the-new-hotness? I already discussed this with someone from flathub community and they will be happy to have this kind of feature.

**Comment by jeremycline** [comment]
Seems reasonable

**Comment by Zlopez** [comment]
## Implementation details
This feature needs a new module that will communicate with Github using [Github APIv4](https://developer.github.com/v4/). Every time we catch new release of project mapped to Flathub we will create a new issue on `flathub/<mapped name>` with notification about new release. What is still not solved is how to enable/disable these notifications. I already have two possible solution for this:

1. Read value from `flathub.json` file, this needs some coordination with Flathub guys.
2. Public repository similar to [pagure_scm_requests](https://pagure.io/releng/fedora-scm-requests), but this will need a PR to be created each time there is a change.

**Comment by Zlopez** [comment]
After some discussion in CPE Team, we decided that this doesn't fit our Mission Statement, so I'm closing this issue.
