### ISSUE TITLE
Use Fedora package name

### ISSUE THREAD

**Issue by mathstuf** [fedora-infra/the-new-hotness#21]
For Haskell package update emails, I'm getting the Hackage name for the package (e.g., xml) rather than the Fedora package name (ghc-xml).

**Comment by mathstuf** [comment]
Might be anyita doing this. It's the email from `notifications@` that has the wrong name.

**Comment by ralphbean** [comment]
Can you paste the full contents of one of those emails here?

**Comment by mathstuf** [comment]
```
Subject: A new version of "xml" has been detected: "1.3.14" in advance of "1.3.13"

[-- Autoview using cat --]
A new version of "xml" has been detected:  "1.3.14" in advance of "1.3.13"
        https://release-monitoring.org/project/1044/

-- 
You received this message due to your preference settings at
https://apps.fedoraproject.org/notifications//mathstuf.id.fedoraproject.org/email/27586
```

**Comment by ralphbean** [comment]
Yes, this from anitya.  It occurs to me that we can just swap in the Fedora package name if its known at the time.  One sec...

**Comment by ralphbean** [comment]
@mathstuf, lemme know if anything about fedora-infra/fedmsg_meta_fedora_infrastructure#212 looks off to you.

**Comment by mathstuf** [comment]
Looks sensible to me.
