### ISSUE TITLE
Use dist-git directly for monitoring settings instead of scm-requests repository

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#233]
With recent changes in Pagure, we should use information about monitoring from [dist-git](https://src.fedoraproject.org/) instead of [scm-request](https://pagure.io/releng/fedora-scm-requests/).

This will need change in address where we are looking for information and also the way we are getting the information from the response.

**Comment by pypingou** [comment]
We may be able to extract this information into a single JSON file rather than making you to query hundreds or thousands of packages.

**Comment by Zlopez** [comment]
Implemented in #256
