### ISSUE TITLE
the-new-hotness override a wrong issue in RHBZ

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#234]
A new release report of deepin-terminal from Anitya overrided an ABRT issue:
https://bugzilla.redhat.com/show_bug.cgi?id=1688632
which is private.

EDIT BY puiterwijk: Posting screenshots of private tickets is *not* a good idea.

**Comment by Zlopez** [comment]
I need to first investigate, what happened.  At the first look I think this is related to way the-new-hotness is finding the issue, that should be used.

**Comment by bowlofeggs** [comment]
This happened to https://bugzilla.redhat.com/show_bug.cgi?id=1542932 as well.

**Comment by puiterwijk** [comment]
@Zlopez I have removed your screenshot. If a bug is marked Private in bugzilla, it is *NOT* okay to share screenshots of them in a public ticket.

**Comment by Zlopez** [comment]
@puiterwijk Sorry, I just copied the post from the original issue on Anitya.

**Comment by Zlopez** [comment]
@bowlofeggs I don't know what is happening, this never happened till we moved to openshift. I need to go through the logs and see if there is anything suspicious.

**Comment by cuviper** [comment]
Here's another case: https://bugzilla.redhat.com/show_bug.cgi?id=1511821#c4

**Comment by Zlopez** [comment]
I found the pattern that is causing this. This only happens, if there is no previous bugzilla issue for the package.
