### ISSUE TITLE
Koji fedmsgs are different in stg and prod

### ISSUE THREAD

**Issue by abompard** [fedora-infra/the-new-hotness#250]
According to the [Fedora Messaging progress board](https://github.com/orgs/fedora-infra/projects/2), Koji's Fedora Messaging port is in staging but not in prod. The way the AMQP-ZMQ bridges work currently is that fedmsg messages are published to AMQP without change, thus with the message content in a `msg` key [this bug has been reported](https://github.com/fedora-infra/fedmsg-migration-tools/issues/20). As a result, in staging the-new-hotness gets messages from the AMQP version of Koji, but will receive in prod messages that will look different (message content in the `msg` key). Until the bridges are fixed to squash the `msg` key, the prod version of The New Hotness will crash on Koji messages.

**Comment by Zlopez** [comment]
Thanks for reporting. Do Koji have a fedora messaging scheme ready, so I could use it?

**Comment by Zlopez** [comment]
I see the bug is closed, so I will close this one as solved.
