### ISSUE TITLE
[Question] strip down hotness/anitya.py?

### ISSUE THREAD

**Issue by dcermak** [fedora-infra/the-new-hotness#261]
I've been taking a look at the-new-hotness and it appears to me that `hotness/anitya.py` contains quite a lot of unused code?

The following methods of `Anitya` are used nowhere else in this project:
- `map_new_package`
- `update_url`
- `add_new_project`
- `get_project_by_package`
- `search_by_homepage`

which leaves only `Anitya.force_check` being actively used inside the-new-hotness or am I mistaken?

If not, how about dropping these methods?

**Comment by Zlopez** [comment]
It's possible that some of the code is no longer used. I need to clean it up.
