### ISSUE TITLE
Errors while downloading sources

### ISSUE THREAD

**Issue by TomasKorbar** [fedora-infra/the-new-hotness#302]
Hi,
I would like to ask if there is a way how to make automatic scratch builds
work if you have sources that are not located at some url but are directly in the
dist git. For example here https://bugzilla.redhat.com/show_bug.cgi?id=1835164
scratch build was not executed because the-now-hotness could not
download memcached.sysconfig which is a file stored directly in dist git and thus
does not need to be downloaded.

**Comment by Zlopez** [comment]
We are using `spectool -l` for validation of the sources. Are you using something else?

**Comment by TomasKorbar** [comment]
So what is your advice? Change the source path for example from "memcached.sysconfig" to "file:///memcached.sysconfig"?

**Comment by Zlopez** [comment]
I tried to parse the url you provided manually and this wouldn't work. The-new-hotness considers the URL as valid, if it contains network location, which is not true for local files.

Does this local path works for you with `spectool -g`? If it is working, I consider this an issue on our side and create a fix for this.

**Comment by TomasKorbar** [comment]
Yes,
when i execute "spectool -g", memcached.sysconfig is not downloaded and spectool downloads only sources which are really urls.
