### ISSUE TITLE
Migrate to another CI

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#309]
The-new-hotness is now using CentOS CI, but we have issue with this service and tests are failing for long time because of this.

It will be probably good to consider migration to another CI system. We should investigate which one will be good for this project.

**Comment by ozkanonur** [comment]
What is used behind the CentOS CI? I guess Jenkins?

**Comment by Zlopez** [comment]
CentOS CI is using Jenkins, but I want to migrate to Zuul instead. So it's same as on Anitya.
