### ISSUE TITLE
Manual run of the-new-hotness in Anitya

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/the-new-hotness#31]
I come to know on IRC that the-new-hotness runs twice a day. I would like to propose if someone want a bug of new upstream release available and when Anitya finds new release available when clicked on "Check now" button, it should call the-new-hotness and file a bug immediately.

Today, I added fontforge project in Anitya, clicked on "Check now", it found new release but after waiting for sometime still no but got reported. So I am filing this issue.
Thanks.

**Comment by ralphbean** [comment]
@pnemade, this is not quite true.  the-new-hotness runs "all the time" in response to messages from anitya.

Look further down the page here to see what happened:  https://apps.fedoraproject.org/datagrepper/raw?package=fontforge

The new version of the upstream project fontforge was found by anitya, but at that moment anitya didn't yet know what the name of that project was in Fedora.  It wasn't yet "mapped to a Fedora package".  the-new-hotness saw this, but didn't know what to do and so did nothing.

When you add projects in anitya, if you specify the Distro and Package name in the beginning, this should all work as expected.

**Comment by pnemade** [comment]
I think when I added fontforge in Anitya, I filled all the details but not knowing pkgdb monitoring was OFF for it. See the details added message https://apps.fedoraproject.org/datagrepper/id?id=2015-d2f7f733-89c8-4de9-a7c0-362c323017ae&is_raw=true&size=extra-large

Now what i want to know, if someone enables monitoring later, will the-new-hotness file a bug whereas Anitya already found new upstream is available?

another thing, if some one updated package on his own and the build failed on koji, so latest available build in the repo is still older build for that package. In this case will anitya still try to find new release and the-new-hotness will file a bug?

**Comment by ralphbean** [comment]
> will the-new-hotness file a bug whereas Anitya already found new upstream is available

Nope, but we could add that.  the-new-hotness could listen for pkgdb messages indicating that monitoring was turned on, then it could go and actively query anitya to see if it should file a bug, etc.  I just filed this as #32.

> if some one updated package on his own and the build failed on koji, so latest available build in the repo is still older build for that package. In this case will anitya still try to find new release and the-new-hotness will file a bug?

Yes.  Anitya will still try to find the new release, even if the package *is already built and in the Fedora repos*.  Anitya is pretty much independent of Fedora considerations.

In the case you mentioned, the-new-hotness will only file the bug if it can't find the new release in the koji rawhide buildroot.  So, yes, if the owner attempted a build and it failed, the-new-hotness would still file a bug.

**Comment by pnemade** [comment]
:+1:  I really like above functionality of Anitya and the-new-hotness.

**Comment by tyll** [comment]
On Thu, Mar 12, 2015 at 06:34:23AM -0700, Ralph Bean wrote:
> > will the-new-hotness file a bug whereas Anitya already found new upstream is available
> 
> Nope, but we could add that.  the-new-hotness could listen for pkgdb messages indicating that monitoring was turned on, then it could go and actively query anitya to see if it should file a bug, etc.  I just filed this as #32.

An additional option is to make the-new-hotness also listen on events
that result from adding a new mapping in anitya that includes Fedora.
Not sure if this is already happening.
