### ISSUE TITLE
An unexpected error occurred while downloading the new package sources

### ISSUE THREAD

**Issue by MichaelRiss** [fedora-infra/the-new-hotness#311]
https://bugzilla.redhat.com/show_bug.cgi?id=1895368 is tracking the updates to the thunderbird package. 
anitya or the-new-hotness seem to run into problems and ask that someone opens a bug on "the issue tracker". 
Is this the right place here?

Apart from what I can read in the bugtracker, I have no further information, except that this bug report is suspiciously quiet for a package that may need an urgent update to fix a security issue. Maybe you can make sense of it?

**Comment by Zlopez** [comment]
This means, that the download of the new sources of firefox failed. I need to investigate why this happened.

**Comment by Zlopez** [comment]
Found out the issue.
There was connection timed out, when trying to access the mozilla FTP server :-(
The message should be more clear.
```
curl: (28) Failed to connect to ftp.mozilla.org port 21: Connection timed out
```
