### ISSUE TITLE
Creates bugzilla after rawhide package is updated

### ISSUE THREAD

**Issue by hadess** [fedora-infra/the-new-hotness#314]
This bug filed at 11:52AM UTC:
https://bugzilla.redhat.com/show_bug.cgi?id=1912411
was filed about 10 minutes after the package was updated in rawhide:
https://koji.fedoraproject.org/koji/buildinfo?buildID=1664448

This sort of problem is particularly egregious when I'm also the person doing the upstream releases.

`the-new-hotness` should be able to check whether a package has already been built but not yet deployed in the rawhide repos, and back off when a build is already on-going.

**Comment by Zlopez** [comment]
If you are the upstream guy, you can disable the monitoring entirely. Just go to src.fedoraproject.org and switch monitoring settings.

The Anitya is checking this URL https://gitlab.freedesktop.org/api/v4/projects/hadess%2Fswitcheroo-control/repository/tags and the latest version according to this is 2.4

**Comment by hadess** [comment]
> The Anitya is checking this URL https://gitlab.freedesktop.org/api/v4/projects/hadess%2Fswitcheroo-control/repository/tags and the latest version according to this is 2.4

This isn't the problem I reported though. The problem is that the bug was created in bugzilla even though the package _was_ already up-to-date.

**Comment by Zlopez** [comment]
The-new-hotness is querying the mdapi to compare versions, so it's possible it was not updated yet.

**Comment by hadess** [comment]
> The-new-hotness is querying the mdapi to compare versions, so it's possible it was not updated yet.

I mentioned that this might be the problem in the original comment ;)

**Comment by Zlopez** [comment]
In this case we are on the same page :-)

**Comment by Zlopez** [comment]
I'm closing this, because there isn't much I can do about it.

**Comment by hadess** [comment]
If you can't do anything about it, who's going to get this fixed then?

**Comment by Zlopez** [comment]
I querying the mdapi, if it doesn't have up to date data, there isn't much the-new-hotness could do about it. Or do you think there is a better way to check for the latest version available in Fedora?

**Comment by hadess** [comment]
I would have expected you to file a bug against the mdapi to figure this out with the maintainers of that API.

**Comment by Zlopez** [comment]
You can report it [here](https://pagure.io/mdapi/issues), I'm not sure how often the mdapi database is updated. It's possible that this just hit some window between the updates.

**Comment by hadess** [comment]
It would really have been better if _you_ reported it seeing as you seem to maintain this codebase which uses it. You presumably would know better how the API is used and how it would be best modified to fix this problem.

I've filed https://pagure.io/mdapi/issue/118 so this gets moving otherwise we'll never get anywhere.

**Comment by pypingou** [comment]
> how often the mdapi database is updated

It runs every 20 minutes.
