### ISSUE TITLE
handle master -> rawhide branch change

### ISSUE THREAD

**Issue by nirik** [fedora-infra/the-new-hotness#318]
We today changed all the rpms in src.fedoraproject.org from having a master branch, to having a rawhide branch with a symref 'main'. 

It seems like the-new-hotness at least looks for master to tell if a package is retired: 

hotness/consumers.py:        params = dict(name="master", global_component=package, type="rpm", active=True)
hotness/consumers.py:        # If there are zero active master branches for this package, then it is

This should switch to 'rawhide'

**Comment by Zlopez** [comment]
I don't think the change was necessary, but I will update the-new-hotness.
