### ISSUE TITLE
Add Redis as cache for builds we are watching

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#323]
Currently the-new-hotness is saving the builds_id with bug_id in variable, which prevents us to run multiple instances of the-new-hotness at once, because if the message from koji is received by other instance than the one that started scratch build it doesn't found the bug and just drop the message.

We should use Redis to store this information across multiple hotness instances.

**Comment by ozkanonur** [comment]
@Zlopez  May I know if it's not getting developed by anyone else so I can start working on this ?

**Comment by Zlopez** [comment]
I'm now working on packit support #235, so if you want to take this, feel free to take it.
