### ISSUE TITLE
Update vagrant environment

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#326]
Update vagrant environment to newer Fedora release and clean up the dependencies after redesign.

**Comment by ozkanonur** [comment]
Is there specific reasons for not providing docker or podman environment instead of Vagrant? @Zlopez

**Comment by Zlopez** [comment]
the-new-hotness used vagrant before I started working on it, so I don't know the reasons. My guess is that the vagrant was easier to setup.

**Comment by ozkanonur** [comment]
> the-new-hotness used vagrant before I started working on it, so I don't know the reasons. My guess is that the vagrant was easier to setup.

I think Vagrant is a bit too much for just running apps. If there are no reasons for not using containers, you can create an issue about that and assign me to it, up to you.

**Comment by Zlopez** [comment]
In this case it's setting the whole dev environment for you, not only running app. You can then ssh into it and start work on it.

**Comment by Zlopez** [comment]
But having the container with same setup could be better from resource point of view.

**Comment by Zlopez** [comment]
@ozkanonur Here is the ticket https://github.com/fedora-infra/the-new-hotness/issues/336

**Comment by ozkanonur** [comment]
I think we can achieve same thing on containers but not easy as doing ssh.

Also, better production environment maybe? So we can build the image from CI on each tag and pull the latest one from k8s worker. These are my opinions maybe you can think about.

**Comment by ozkanonur** [comment]
> @ozkanonur Here is the ticket #336

Got it :)

**Comment by Zlopez** [comment]
> I think we can achieve same thing on containers but not easy as doing ssh.
> 
> Also, better production environment maybe? So we can build the image from CI on each tag and pull the latest one from k8s worker. These are my opinions maybe you can think about.

I don't think we need it, the deployment of the image in staging/production is now done easily by pushing to staging or production branch respectively.

**Comment by ozkanonur** [comment]
Understood, as long as we dont need images docker-compose should be enough right? Simple and good enough for doing development.

**Comment by Zlopez** [comment]
Yes I would say so.

**Comment by Zlopez** [comment]
The vagrant container was updated in https://github.com/fedora-infra/the-new-hotness/pull/349, but we should still need to clean the dependencies.
