### ISSUE TITLE
Synchronize GitHub issue labels with news file types

### ISSUE THREAD

**Issue by Zlopez** [fedora-infra/the-new-hotness#338]
It would be easier to comprehend if there were labels connected to news file types. The documentation will then contain this description of news file `{issue-id}.{issue-label}`, which will be much more easier to understand than the current description.

**Comment by ozkanonur** [comment]
What are we gonna do if we have multiple labels? Maybe we should create labels with the prefix ``type:``. So for feature news label can be `type:feature`.

**Comment by Zlopez** [comment]
We should add list of labels in the documentation, but adding `type:` prefix to label is not bad idea.

**Comment by ozkanonur** [comment]
May I know your mail address I have a couple of questions I think its better to ask them privately

**Comment by Zlopez** [comment]
You can send e-mail to my work mail mkonecny@redhat.com I will probably look at it after weekend.

**Comment by ozkanonur** [comment]
Can be nice to know the list of the labels so I can add them to the documentation. I can open PR to solve this issue quickly. Or let me know if you doing it already.

**Comment by Zlopez** [comment]
We would use the same labels as types in current [contribution guide](https://the-new-hotness.readthedocs.io/en/stable/dev-guide.html#release-notes)
