### ISSUE TITLE
"I dunno. Whatever" notifications

### ISSUE THREAD

**Issue by QuLogic** [fedora-infra/the-new-hotness#379]
I keep seeing notifications for `the-new-hotness saw an update for <package>, but .... I dunno. Whatever.`

I don't know what this is supposed to mean, and I don't think it's a very useful notification.

**Comment by Zlopez** [comment]
Do you have any example? I'm not sure what are you talking about.

**Comment by QuLogic** [comment]
Well, it's exactly that, and there is no link to any further details.

An example notification comes with a subject of `the-new-hotness saw an update for golang-github-aws-sdk, but .... I dunno. Whatever.` and contents:

> Notification time stamped 2021-12-14 05:12:59 UTC
>
> the-new-hotness saw an update for golang-github-aws-sdk, but .... I dunno.  Whatever.
>         https://release-monitoring.org/project/7751/

There are also the following mail headers:
> X-Fedmsg-Topic: org.fedoraproject.prod.hotness.update.drop
> X-Fedmsg-Category: hotness
> X-Fedmsg-Package: golang-github-aws-sdk
> X-Fedmsg-Package: golang-github-aws-aws-sdk-go
> X-Fedmsg-Num-Packages: 2

**Comment by Zlopez** [comment]
The New Hotness isn't sending these notifications by itself, so it must be other application that is catching The New Hotness messages and sends this e-mail notification.

I'm not sure what is actually sending these messages (I would expect [FMN](https://github.com/fedora-infra/fmn)). Is this something that was changed recently or it was always like this?

**Comment by QuLogic** [comment]
It's certainly recent, say a few weeks, less than 2 months for sure.

**Comment by QuLogic** [comment]
Here is the message for it: https://apps.fedoraproject.org/datagrepper/id?id=2021-c4d5eeea-9761-4e53-be3f-8cbfe39fafd0&is_raw=true&size=extra-large

**Comment by Zlopez** [comment]
The notification is correct, just the description is not fine.

It will be probably issue in [metainfo for fedmsg](https://github.com/fedora-infra/fedmsg_meta_fedora_infrastructure/), which is not maintained for a while.

**Comment by Zlopez** [comment]
This shouldn't be issue anymore with FMN 2.0
