### ISSUE TITLE
Scratch build failed - https://bugzilla.redhat.com/show_bug.cgi?id=2036387

### ISSUE THREAD

**Issue by abraunegg** [fedora-infra/the-new-hotness#386]
```
Scratch build failed. Details bellow:

GenericError: File upload failed: cli-build/1640974731.6031349.lYdCJtHi/onedrive-2.4.15-1.fc34.src.rpm
Traceback:
  File "/usr/local/lib/python3.9/site-packages/hotness/use_cases/package_scratch_build_use_case.py", line 56, in build
    result = self.builder.build(request.package, request.opts)
  File "/usr/local/lib/python3.9/site-packages/hotness/builders/koji.py", line 198, in build
    output["build_id"] = self._scratch_build(session, package.name, srpm)
  File "/usr/local/lib/python3.9/site-packages/hotness/builders/koji.py", line 451, in _scratch_build
    session.uploadWrapper(source, serverdir)
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 3000, in uploadWrapper
    self.fastUpload(localfile, path, name, callback, blocksize, overwrite, volume=volume)
  File "/usr/lib/python3.9/site-packages/koji/__init__.py", line 2935, in fastUpload
    raise GenericError("File upload failed: %s/%s" % (path, name))
```

**Comment by Zlopez** [comment]
This seems more like issue with the server where the upload should go, I would try to restart the scratch build manually and see if the issue happens again.

**Comment by abraunegg** [comment]
@Zlopez 
> This seems more like issue with the server where the upload should go, I would try to restart the scratch build manually and see if the issue happens again.

I have zero access permissions to do that

**Comment by Zlopez** [comment]
Could you link the bugzilla issue where you found the error?

**Comment by abraunegg** [comment]
@Zlopez 
the bugzilla link is in the title ...

**Comment by Zlopez** [comment]
I restarted the update from Anitya and the scratch build was successful, so it was only a temporary error on Koji side.

**Comment by abraunegg** [comment]
@Zlopez 
Thanks greatly appreciated.

Unrelated question: Are you able to re-configure koji to rebuild the latest 2.4.15 for fc34, fc35 & fc36 - as right now it is only being rebuilt for fc35, fc36 ?

**Comment by Zlopez** [comment]
Unfortunately I don't have permissions to do that, it will be better to contact the packager who is taking care of the package.
