### ISSUE TITLE
Command '['git', 'commit', '-a', '-m', 'Update to 2.35.2 (#2050122)']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by mcatanzaro** [fedora-infra/the-new-hotness#395]
Something broke here:

https://bugzilla.redhat.com/show_bug.cgi?id=2050122#c1

**Comment by Zlopez** [comment]
This looks like a duplicate of https://github.com/fedora-infra/the-new-hotness/issues/368

**Comment by mcatanzaro** [comment]
yes
