### ISSUE TITLE
Wrong update notification (most)

### ISSUE THREAD

**Issue by adrianreber** [fedora-infra/the-new-hotness#42]
I got this new release notification which is wrong: https://bugzilla.redhat.com/show_bug.cgi?id=1209680

Packages has not been updated for more than 8 years. This probably related to the version 5.0.0-10.a.1 in rawhide and the version of the upstream package 5.0.0a.

**Comment by ralphbean** [comment]
IMHO, to fix this we should first write a couple dozen test cases for the helper code in ``hotness/helpers.py`` (the stuff that does the version comparison).  Then, once we're sure we won't introduce any regressions, we can take measures to handle this case where 5.0.0 (in fedora) should be considered newer than 5.0.0a (upstream)... (even though we really have the same versions in place).

**Comment by ralphbean** [comment]
I stubbed out a test suite in 2249110, but when I went in to try and find a way to get 5.0.0 to evaluate as newer than 5.0.0a, it became a quagmire.  I don't think we're going to be able to handle edge cases like these.

If anyone has input on a workaround, the patch would be much appreciated (you can add this as a test case to verify).
