### ISSUE TITLE
Weird behavior of  Upstream Release Monitoring with mock-core-configs

### ISSUE THREAD

**Issue by praiskup** [fedora-infra/the-new-hotness#437]
Per one of the comments in https://bugzilla.redhat.com/show_bug.cgi?id=2060422

>> Latest upstream release: 37.2-1
>> Current version/release in rawhide: 37.2-1.fc37
>
> This looks weird ^^^.  The second Version-Release contains the %dist tag.

Because of this, the version with release seems to be considered "older"
than the one in upstream (without dist tag).  With our release process, we are
getting these weird bug reports.

**Comment by Zlopez** [comment]
What do you think is the good approach here, to remove the %dist tag from retrieved version?

**Comment by Zlopez** [comment]
So solution here is to check if the version contains a %dist tag and if it does remove it before doing anything else.
