### ISSUE TITLE
When attach patch to bugzilla should also write where is the source 

### ISSUE THREAD

**Issue by sergiomb2** [fedora-infra/the-new-hotness#48]
Hi, 
After a Scratch build succeeded, I got the patch but I don't know where is the source .
I though automate the update from my laptop but I haven't the link of the source . 

Thanks ,

**Comment by pypingou** [comment]
Isn't the location of the sources specified in the spec file?

**Comment by sergiomb2** [comment]
yes , but before do scratch build , you need download source and upload it into the builder isn't it ? 
If this project already does that , why not show how it does ? , I or other developer would like automate to task of commit it into master (download the source , upload it and commit the sources file and the .gitingore file and request a build ) , when we think we should do that.

**Comment by pypingou** [comment]
Commit to master to make a new update should not be automated. 
There might be new libraries bundled, a license change, invalid libraries used, dependency added/removed. Many things can change between two version of an application and doing the update fully automated is a bad idea for each of them.

That being said, the code managing the download in the-new-hotness is at: https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/buildsys.py#L115

**Comment by sergiomb2** [comment]
Hi, 
After a scratch build succeeded and when I think that scratch build should go to rawhide , I'd like have a script that automate it , but I use my credentials to do it .

**Comment by ralphbean** [comment]
@sergiomb2 apply the patch and try looking at ``spectool -g your_specfile.spec``.  That should pull down the latest sources from upstream.

@pypingou is right though -- you should be careful to inspect new upstream releases for bundled content and changed licenses.

**Comment by sergiomb2** [comment]
Hi  Ralphbean , 
OK. spectool is a fine tool, do what I expect and this bug is closed correctly . 

Now as a packager, I know that a package is fine to update. So I just want a tool that do all steps for me, as one add-on to release-manager and this the-new-hotness . I will use a modified buildsys.py to do what I'm thinking .

Thanks.

**Comment by ralphbean** [comment]
> I just want a tool that do all steps for me

I know the feeling!  :grin:
