### ISSUE TITLE
Bugs and builds immediately when turning on monitoring

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/the-new-hotness#49]
It would be nice if bugs and builds were filed/fired immediately after turning on monitoring if the package is currently out of date.  Currently you can turn it on, but nothing happens until upstream updates again.

**Comment by tomhughes** [comment]
Is that not exactly what df8fddd16c134bd095dd15b941c274b7382408c2 does? Certainly when I turned on "bugs and builds" for some packages the other day I immediately got bugs filed...

**Comment by ralphbean** [comment]
Yeah, this is how it's supposed to work now.
