### ISSUE TITLE
Submit patch to bugzilla

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/the-new-hotness#5]
When hotness does its scratch build, it should also attach the patch that it generated to the bugzilla ticket that it created.

**Comment by rahulsundaram** [comment]
Any update on this?

**Comment by ralphbean** [comment]
None yet.  However, you can grab the srpm from the scratch build and use 'fedpkg import' (someone told me they were doing this.. I think it was @voxik).

**Comment by rahulsundaram** [comment]
interesting!  thanks for the tip
