### ISSUE TITLE
Manually trigger builds/bugs for updated packages

### ISSUE THREAD

**Issue by jasontibbitts** [fedora-infra/the-new-hotness#50]
There are two situations I can see where it might be nice to manually trigger a check against anitya and fire builds/bugs as necessary:

When you've set everything up for monitoring but the package is already outdated, tnh won't currently do anything.  Even if this is changed in the future, existing packages in that situation will be outdated with no bugs filed.

If you want to have monitoring off most of the time, but still be able to manually trigger an update check.  (For a package which updates very quickly, perhaps.)

**Comment by ralphbean** [comment]
> When you've set everything up for monitoring but the package is already outdated, tnh won't currently do anything. Even if this is changed in the future, existing packages in that situation will be outdated with no bugs filed.

OK, I think this is currently taken care of in two cases:

- When you map an upstream in anitya to a Fedora package, tnh responds by either filing a bug if pkgdb says that's OK, or it forces an anitya check if anitya doesn't provide a version with the mapping.  See 4cef2de3.
- Or, when you toggle monitoring in pkgdb, tnh tries to map the package to a project in anitya if its not already there, and it forces a fresh check of the version at that time.  See df8fddd1.

> If you want to have monitoring off most of the time, but still be able to manually trigger an update check. (For a package which updates very quickly, perhaps.)

How would this work?  You have monitoring off, but you want to turn it on just for a moment to see if a bug gets filed?  If so, that seems circuitous.  Why not check anitya with your own eyes if you're bothering to turn the pkgdb flag on and back off again.  I'm not sure I'd want to bear the burden of maintaining a use case like that.

**Comment by jasontibbitts** [comment]
Well, I filed this because either you or Pingou thought it was and interesting case.

I can try to dredge up the IRC convo if you really want it.  But I will say that toggling the updates check and having the system file the ticket and do a scratch build is a good bit more convenient than checking anitya manually, sitting around waiting for bugzilla to load, typing up a ticket, sitting around waiting for bugzilla to accept the ticket, editing the spec, fetching the fresh source, building an srpm, uploading it to koji, waiting for the scratch build to complete, waiting for bugzilla to load, pasting in the result of the koji build and waiting for bugzilla to accept the ticket.  I would hope that you could see the utilitt, at least.

But I do think that kind of thing would be better served by a "manual check" button that appears in pkgdb when monitoring is off.

**Comment by ralphbean** [comment]
I guess I don't understand why you don't just turn monitoring on in the first place?
