### ISSUE TITLE
Couple package update BZ tickets not created

### ISSUE THREAD

**Issue by siwinski** [fedora-infra/the-new-hotness#51]
I have a couple packages that Anitya has found updates for but no BZ ticket has been created.

Package: [php-when](https://admin.fedoraproject.org/pkgdb/package/php-when/)
Rawhide version: 0.3
Anitya found version: [v2.0.0](https://release-monitoring.org/project/3625)

Package: [php-xmlseclibs](https://admin.fedoraproject.org/pkgdb/package/php-xmlseclibs/)
Rawhide version: 1.3.1
Anitya found version: [1.4.0](https://release-monitoring.org/project/6614)

Is something wrong with the packages or package info or was this just a the-new-hotness hiccup?

**Comment by ralphbean** [comment]
In the case of php-when, it looks like that version was found about 6 months ago, and I see that there were some API changes in the interaction between hotness and pkgdb about that time.  There could've been a bug in play in the middle of the changeover that got that package lost.

In the case of php-xmlseclibs, I see from [the datagrepper history](https://apps.fedoraproject.org/datagrepper/raw?category=hotness&category=anitya&category=pkgdb&package=php-xmlseclibs) that anitya found the update, and hotness responded to the anitya message, but it found from pkgdb that the monitoring flag was turned off, and so it did nothing.
