### ISSUE TITLE
Tickets reported for `Assignee: extras-orphan@fedoraproject.org`

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#527]
[This](https://bugzilla.redhat.com/show_bug.cgi?id=2131395) ticket caught my attention, especially this:

~~~
Assignee: extras-orphan@fedoraproject.org
~~~

As far as I know, the package used to be retired, but it changed with its [unretirement not a long time ago](https://pagure.io/releng/issue/10879). So why the `extras-orphan@fedoraproject.org` assignee?

@mkoncek FYI

**Comment by nirik** [comment]
If you look at https://src.fedoraproject.org/rpms/lucene you can see... it seems to have a bugzilla override for 'orphan'. 

No idea why or who set that, but clearing that should fix it.

**Comment by Zlopez** [comment]
I'm closing this, because it's not an issue on the-new-hotness side.
