### ISSUE TITLE
bug reported for "latest" version instead of newly "retrieved" version

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/the-new-hotness#534]
originally reported here:
https://github.com/fedora-infra/anitya/issues/1496

It looks like the-new-hotness uses either the "biggest" version when filing new bugs on RHBZ instead of the one that was actually retrieved.

This can result in bugs getting reported for the wrong version, for example, if a version filter was set up to exclude pre-releases but there already were pre-releases in anitya's database.

**Comment by Zlopez** [comment]
Fixed in https://github.com/fedora-infra/the-new-hotness/pull/537
