### ISSUE TITLE
Trackers are not created for "ruby"

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#539]
Yesterday, new version of Ruby was released. release-monitoring.org properly [detected](https://release-monitoring.org/project/4223/) the release. However, no trackers were created. I have just received this FMN notification:

~~~
Notification time stamped 2022-11-24 18:18:52 UTC

the-new-hotness saw an update for ruby, but .... I dunno.  Whatever.
	https://release-monitoring.org/project/4223/

--
You received this message due to your preference settings at 
https://apps.fedoraproject.org/notifications/vondruch.id.fedoraproject.org/email/50912
~~~

That is not very helpful :/

**Comment by Zlopez** [comment]
Found the reason why it's dropping the update, it seems that there is some issue with metadata in fedora.

```
[2022-11-28 13:37:10,269 hotness.validators.mdapi INFO] Comparing upstream 3.1.3 against repo 6.4.0-172.fc38
[2022-11-28 13:37:10,270 hotness.validators.mdapi INFO] 3.1.3 is not newer than 6.4.0-172.fc38
[2022-11-28 13:37:10,270 hotness.hotness_consumer INFO] Message doesn't contain newer version of 'ruby'. Dropping.
```

Hotness is checking the metadata in mdapi(https://mdapi.fedoraproject.org/koji/srcpkg/ruby) and as you can see this says that there is version 6.4.0 available in koji.

Anyway this isn't issue in the-new-hotness, so I'm closing this ticket.

Regarding the notification e-mail: this is a known issue, but wouldn't be solved till the new version of FMN will be available.

**Comment by voxik** [comment]
Typical MDAPI issue :angry: Thx for analysis.

BTW would it be possible to include such analysis somewhere in the notification or elsewhere where it would be discoverable?

**Comment by voxik** [comment]
Apparently, this does not happen for the first time :man_facepalming: 

https://pagure.io/mdapi/issue/115

**Comment by Zlopez** [comment]
> Typical MDAPI issue angry Thx for analysis.
> 
> BTW would it be possible to include such analysis somewhere in the notification or elsewhere where it would be discoverable?

It should be part of the e-mail with notification, at least it should say it's not newer, but the fedmsg meta package that is used by FMN to translate the messages is not updated for long time. But this should work again with new FMN that will support fedora messaging.

**Comment by Zlopez** [comment]
> Apparently, this does not happen for the first time man_facepalming
> 
> https://pagure.io/mdapi/issue/115

The mdapi could use some love as well.
