### ISSUE TITLE
Failed to kick off scratch build due to sha256sum error

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/the-new-hotness#54]
I have no idea why there happened no scratch-build but here it is https://bugzilla.redhat.com/show_bug.cgi?id=1245760#c1 and one more example https://bugzilla.redhat.com/show_bug.cgi?id=1245761#c1

**Comment by sergiomb2** [comment]
Yesterday the same thing happened to me 

https://bugzilla.redhat.com/show_bug.cgi?id=1250051

**Comment by ralphbean** [comment]
Huh, so right here is where the problem lives:  https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/buildsys.py#L107-L134  It is failing to find the name of the tarball on either line 109 or 116 and then later on lines 125/126 trying to find the sha sum of that failed filename.

I suspect that there was some change in either the spectool or fedpkg commands that is causing this but haven't yet made time to investigate further.  Perhaps the comments above can help someone get to the bottom of it?

**Comment by pypingou** [comment]
Looks like spectools:
````
$ ls
0001-Remove-vte-check-in-the-configure.ac.patch                 guake-0.2.2-fix_vte.patch  sources
0001-set-default-value-for-apps-guake-general-debug_mode.patch  guake.spec
$ spectool -A guake.spec 
Source0: guake-0.7.2.tar.gz
Patch5: 0001-Remove-vte-check-in-the-configure.ac.patch
Patch6: 0001-set-default-value-for-apps-guake-general-debug_mode.patch
$ spectool -g guake.spec 
$
$ ls
0001-Remove-vte-check-in-the-configure.ac.patch                 guake-0.2.2-fix_vte.patch  sources
0001-set-default-value-for-apps-guake-general-debug_mode.patch  guake.spec
````

**Comment by pypingou** [comment]
Ignore my previous post, I seem to be missing some coffee...
