### ISSUE TITLE
GenericError: Invalid method: krb_login

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/the-new-hotness#549]
Scratch build failed. Details below:

GenericError: Invalid method: krb_login
Traceback:
  File "/usr/local/lib/python3.10/site-packages/hotness/use_cases/package_scratch_build_use_case.py", line 56, in build
    result = self.builder.build(request.package, request.opts)
  File "/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py", line 195, in build
    session = self._session_maker()
  File "/usr/local/lib/python3.10/site-packages/hotness/builders/koji.py", line 422, in _session_maker
    result = koji_session.krb_login(
  File "/usr/lib/python3.10/site-packages/koji/__init__.py", line 2362, in __call__
    return self.__func(self.__name, args, opts)
  File "/usr/lib/python3.10/site-packages/koji/__init__.py", line 2874, in _callMethod
    raise err

If you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues

**Comment by Zlopez** [comment]
Could you provide the bugzilla ticket as well?

**Comment by romulasry** [comment]
the-new-hotness isn't on bugzilla.

**Comment by romulasry** [comment]
> Could you provide the bugzilla ticket as well?

https://bugzilla.redhat.com/show_bug.cgi?id=1976751#c12

**Comment by penguinpee** [comment]
I'm experiencing the same issue (https://bugzilla.redhat.com/show_bug.cgi?id=2167997) and @rathann reported in #fedora-devel having seen several as well.

**Comment by rathann** [comment]
Several others:
https://bugzilla.redhat.com/show_bug.cgi?id=2143353#c10
https://bugzilla.redhat.com/show_bug.cgi?id=1949144#c34
https://bugzilla.redhat.com/show_bug.cgi?id=2158351#c8
https://bugzilla.redhat.com/show_bug.cgi?id=2167149

**Comment by Zlopez** [comment]
From first glance, it seems that there was something changed in koji library, I will try to investigate more and probably fix this today.

**Comment by Zlopez** [comment]
This fix is now deployed on production.
