### ISSUE TITLE
no bug reported for newer harfbuzz release

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/the-new-hotness#55]
harfbuzz-1.0.2 released 5 days ago. I don't think anything has changed in anitya so the-new-hotness should have reported new upstream version 1.0.2 availability.

Anything wrong going on with the-new-hotness?

**Comment by nirik** [comment]
It was actually anitya that was stuck. :( 

I've restarted it's checking queue so hopefully it should notice the release very soon here.

**Comment by pnemade** [comment]
Thanks it worked now :+1:

**Comment by pnemade** [comment]
let's close this.
