### ISSUE TITLE
"new" version 0.4.9 overrides bug title version 0.5.1 in bug report

### ISSUE THREAD

**Issue by decathorpe** [fedora-infra/the-new-hotness#553]
This is really strange:
https://bugzilla.redhat.com/show_bug.cgi?id=2173340#c2

Bug was opened by the-new-hotness for version 0.5.0 and 0.5.1, and then upstream released 0.4.9, which was not considered the "latest", but it still overwrite the 0.5.1 version in the bug report.

**Comment by Zlopez** [comment]
This is correct, because it is still newer than the one in Fedora (`Current version/release in rawhide: 0.4.7-2.fc38`), even if it's older than the one considered latest by Anitya.

**Comment by decathorpe** [comment]
While it's correct to detect 0.4.9 as a new version, having it override the bug title is unexpected.

**Comment by Zlopez** [comment]
That is something we should fix.

**Comment by Zlopez** [comment]
This was already fixed in https://github.com/fedora-infra/the-new-hotness/pull/555 and released in version 1.2.3
