### ISSUE TITLE
Could not add anitya project. Not logged in.

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/the-new-hotness#56]
I am seeing this kind of message for many other projects but could not understand why its coming besides some users saying they are already logged into Anitya.

https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.hotness.project.map

Can someone help to understand this?

**Comment by tomhughes** [comment]
I just got this for libosmium. At 1214 UTC I got this:

```
A new version of "libosmium" has been detected:  "v2.4.0" newer than "v2.3.0", packaged as "libosmium"
	https://release-monitoring.org/project/7023/
```

but no bug was filed despite "bugs and builds" being set at https://admin.fedoraproject.org/pkgdb/package/libosmium/ so I tried turned that off and on again to force a new check and then at 1518 UTC I got this:

```
hotness tried to map libosmium to an upstream project, but failed:  "Could not add anitya project.  Not logged in."
	https://release-monitoring.org/project/7023/
```

**Comment by pnemade** [comment]
Please someone from developers reply. I think this is happening since last 3 weeks now.
@ralphbean can you help here?

**Comment by ralphbean** [comment]
Sorry, been busy with bodhi2 here.  I think it has a session with anitya that just expires.  Some logic will need to be added that tells it how to log back in when that happens.  Let me restart it and see if that fixes it (short term).

**Comment by ralphbean** [comment]
Well, I tried that and then tried toggling the monitor flag on libosmium again, but it didn't work:  https://apps.fedoraproject.org/datagrepper/raw?package=libosmium

hotness still thinks that it isn't logged in, so, something else must be up.

**Comment by ralphbean** [comment]
Can duplicate the login failure using the ``hotness.anitya`` module on my laptop.

**Comment by ralphbean** [comment]
Using this to test, if anyone else wants to mess with it in the meantime:

```python
import hotness.anitya

client = hotness.anitya.Anitya()
client.login("YOUR_USERNAME", "YOUR_PASSWORD")
print client.is_logged_in
```

**Comment by ralphbean** [comment]
@puiterwijk, @pypingou, do either of you have any ideas on this one?  I'm stuck for the moment.

**Comment by tomhughes** [comment]
It seems that when `login` follows the redirect back from id.fedoraproject.org to release-monitoring.org the arguments it passes are not enough to convince release-monitoring.org that we are no logged in.

**Comment by puiterwijk** [comment]
I have patches for both sides of the story, sending them in

**Comment by puiterwijk** [comment]
Note: this probably broke right after we moved to Ipsilon in Fedora Infrastructure, as that should always decide to use POST responses.

**Comment by puiterwijk** [comment]
Note2: the previous statement is NOT a promise, Ipsilon might still send a redirect reply in some cases, but the chance of it using POST is higher.
When implementing OpenID, expect either, do not assume one or the other!

**Comment by pypingou** [comment]
New anitya released and pushed to prod with @puiterwijk 's patch

**Comment by pypingou** [comment]
``
>>> print client.is_logged_in
True
``
With @puiterwijk 's patch applied to the-new-hotness (doesn't work otherwise)

**Comment by ralphbean** [comment]
I'm glad I asked :whew:

**Comment by tomhughes** [comment]
Although this is no longer erroring, it still doesn't seem to be showing any inclination to actually open a bug...
