### ISSUE TITLE
DownloadException: There is a syntax error in updated specfile. See attached diff for the changes. mesa

### ISSUE THREAD

**Issue by romulasry** [fedora-infra/the-new-hotness#564]
Upstream Release Monitoring 2023-05-10 17:21:47 UTC

Scratch build failed. Details below:

DownloadException: There is a syntax error in updated specfile. See attached diff for the changes.
Traceback:
  File "/usr/local/lib/python3.11/site-packages/hotness/use_cases/package_scratch_build_use_case.py", line 56, in build
    result = self.builder.build(request.package, request.opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hotness/builders/koji.py", line 201, in build
    new_sources = self._spec_sources(specfile, tmp)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hotness/builders/koji.py", line 337, in _spec_sources
    raise DownloadException(msg)

If you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues

https://bugzilla.redhat.com/show_bug.cgi?id=2190131

**Comment by Zlopez** [comment]
This seems like I messed something up when handling the error. The `DownloadException` is thrown before the spec file is even available. So the error message should be different.

**Comment by Zlopez** [comment]
Digging into this more I found out that the updated spec file is available, but the `DownloadException` doesn't provide it, I need to fix this.
