### ISSUE TITLE
Failed to file bug for new available package

### ISSUE THREAD

**Issue by xfgusta** [fedora-infra/the-new-hotness#577]
Yesterday, a new version of [bfs](https://github.com/tavianator/bfs/releases/tag/3.0) was released, but the-new-hotness failed to notify me or file a bug. I received a notification after modifying the "Version scheme" on release-monitoring.org:

> Notification time stamped 2023-07-14 16:15:07 UTC
> 
> the-new-hotness saw an update for bfs, but .... I dunno.  Whatever.
>         https://release-monitoring.org/project/276209/
> 
> --
> You received this message due to your preference settings at
> https://apps.fedoraproject.org/notifications/xfgusta.id.fedoraproject.org/email/65049

**Comment by Zlopez** [comment]
If the release-monitoring didn't catch it, then the-new-hotness couldn't do much about it. It relies on messages published by release-monitoring.
