### ISSUE TITLE
Don't create new bz ticket for packages in ASSIGNED state

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#58]
I don't think it makes sense to create new BZ ticket in ASSIGNED state. That typically means somebody is working on that package, or had some insights why the update is not done yet. E.g.

rubygem-bundler:
https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=POST&bug_status=MODIFIED&bug_status=ON_DEV&bug_status=ON_QA&bug_status=VERIFIED&bug_status=RELEASE_PENDING&component=rubygem-bundler&list_id=3784124&product=Fedora&query_format=advanced

rubygem-sup:
https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&bug_status=POST&bug_status=MODIFIED&bug_status=ON_DEV&bug_status=ON_QA&bug_status=VERIFIED&bug_status=RELEASE_PENDING&component=rubygem-sup&list_id=3784124&product=Fedora&query_format=advanced

**Comment by ralphbean** [comment]
Agreed.  Makes sense.

**Comment by ralphbean** [comment]
After a first look into this, I'm not sure what's going on.  It seems like we explicitly set the bug status to `NEW`.  We have a ``'bug_status'`` config value for it, and it is set to NEW in both the example dev config as well as our production config.

**Comment by ralphbean** [comment]
For example:  https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/hotness/templates/hotness.py#n41

**Comment by ralphbean** [comment]
Yeah, I don't think there's anything for us to do here.  @voxik, can you clarify what you mean?

**Comment by voxik** [comment]
Let me give an example. There is some update ticket [1], somebody looked into it and changed its state to ASSIGNED. But once the bug is not in NEW state, it is ignored by the-new-hotness and new ticket is opened [2] as soon as new version is detected and that makes no sense.


[1] https://bugzilla.redhat.com/show_bug.cgi?id=1172650
[2] https://bugzilla.redhat.com/show_bug.cgi?id=1222296

**Comment by ralphbean** [comment]
OH!  I see.  Can fix!
