### ISSUE TITLE
How does the-new-hotness handle a repo change?

### ISSUE THREAD

**Issue by osalbahr** [fedora-infra/the-new-hotness#586]
The build for [Bug 2212029 - neofetch-7.3.10 is available](https://bugzilla.redhat.com/show_bug.cgi?id=2212029) and I think it might be because of the repo changing (see the error message below).

i.e. neofetch-7.3.10.tar.gz is in https://github.com/hykilpikonna/hyfetch/releases/tag/neofetch-7.3.10

```
Scratch build failed. Details below:

BuilderException: Build failed:
Command '['rpmbuild', '-D', '_sourcedir .', '-D', '_topdir .', '-bs', '/var/tmp/thn-88z36_qq/neofetch.spec']' returned non-zero exit status 1.

StdOut:
setting SOURCE_DATE_EPOCH=1692230400
error: Bad file: ./neofetch-7.3.10.tar.gz: No such file or directory

RPM build errors:
    Bad file: ./neofetch-7.3.10.tar.gz: No such file or directory


Traceback:
  File "/usr/local/lib/python3.11/site-packages/hotness/use_cases/package_scratch_build_use_case.py", line 56, in build
    result = self.builder.build(request.package, request.opts)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hotness/builders/koji.py", line 229, in build
    raise BuilderException(

If you think this issue is caused by some bug in the-new-hotness, please report it on the-new-hotness issue tracker: https://github.com/fedora-infra/the-new-hotness/issues
```

What is the proper course of action for such cases? Should the-new-hotness flag that the repo changed, for example?

**Comment by Zlopez** [comment]
In this case the [spec file in neofetch source repository](https://src.fedoraproject.org/rpms/neofetch/blob/rawhide/f/neofetch.spec) needs to be updated to point to correct source. Hotness is just trying to do the scratch build and it doesn't analyze the result, just notify the maintainer that something went wrong.

**Comment by osalbahr** [comment]
Makes sense, thx for clarifying. I am closing this since the main question was answered.

Out of curiosity, how did Hotness pickup that Hyfetch maintains a fork of `neofetch` and concluded that "neofetch-7.3.10 is available"?

**Comment by Zlopez** [comment]
Hotness is taking the information about that from the release-monitoring.org project. [Here is the neofetch project](https://release-monitoring.org/project/16261/).

**Comment by Zlopez** [comment]
@kees-closed It will be best to start this discussion on fedora-devel mailing list or https://discussions.fedoraproject.org. I don't know that much about Fedora packaging to be able to answer your questions.
