### ISSUE TITLE
Stop "Failed to kick off scratch build" please?

### ISSUE THREAD

**Issue by cicku** [fedora-infra/the-new-hotness#59]
PLZ, could this dumb [ft]ool stop throwing out errors like this?

I don't care if it scratches builds or not, especially when it fails due to errors not caused by myself! (In this case, caused by wrong syntax imported from wiki)

I hope you can try...except errors like this.

https://bugzilla.redhat.com/show_bug.cgi?id=1229511

**Comment by ralphbean** [comment]
You can turn it off by setting it to "bugs only" in pkgdb:  https://admin.fedoraproject.org/pkgdb/package/zmap/
