### ISSUE TITLE
Scratch build notified on review request

### ISSUE THREAD

**Issue by remicollet** [fedora-infra/the-new-hotness#60]
For now "rawhide" build are notified on upstream monitoring bug, very nice.

Would be a great feature to notify, "scratch" build on review request.

**Comment by ralphbean** [comment]
Interesting, yes.  :)

**Comment by ralphbean** [comment]
I like it!  But instead of implementing this, I'm going to propose that we defer the functionality to the in-development new review system called [fresque](https://github.com/fedora-infra/fresque).

Thanks for the idea @remicollet!

**Comment by ralphbean** [comment]
On second thought, this could be relatively easy.  I'll give it another look.

**Comment by remicollet** [comment]
Nice, thanks
