### ISSUE TITLE
Missed ticket for Ruby 3.3.6

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#603]
It seems that Anytia properly noticed [Ruby 3.3.6](https://release-monitoring.org/project/4223/), but there was [not reported ticket](https://bugzilla.redhat.com/buglist.cgi?bug_status=NEW&bug_status=ASSIGNED&classification=Fedora&component=ruby&list_id=13526048&product=Fedora&product=Fedora%20EPEL) in Fedora for some reason

**Comment by Zlopez** [comment]
We recently started to have issues with dist-git in Fedora, so it could be caused by the-new-hotness unable to get the monitoring setting from dist-git. I will look at it.

**Comment by Zlopez** [comment]
Found the [message](https://apps.fedoraproject.org/datagrepper/v2/id?id=93896924-3642-4364-bb89-cf5ff9e1b066&is_raw=true&size=extra-large) for the missing version, the problem was caused by bugzilla. It was probably in maintenance at the time. I can re-retrive the version, so the bug is filled, if you want.

**Comment by voxik** [comment]
> I can re-retrive the version, so the bug is filled, if you want.

That would be nice if that is not a big hassle. Thank you for looking into it.

**Comment by voxik** [comment]
> > I can re-retrive the version, so the bug is filled, if you want.
> 
> That would be nice if that is not a big hassle. Thank you for looking into it.

I have already build the updates, so the tickets would not have any value. Closing this now and once again thx for investigation 👍

**Comment by Zlopez** [comment]
Sorry, I was sick for last two days, so I didn't get to that.

**Comment by voxik** [comment]
> Sorry, I was sick for last two days, so I didn't get to that.

No worries. Glad you feel better 👍
