### ISSUE TITLE
Wrong version substitution

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#73]
Looking into [1], I'd say that the-new-hotness somehow wrongly substitutes the version. Please notice the:

```
Getting https://rubygems.org/gems/fog-sakuracloud-v1.3.3.gem to ./fog-sakuracloud-v1.3.3.gem
```

and especially the **v** in front of the version. I have no idea where it comes from. It can be only the-new-hotness IMO (if it is not Anitya)

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1210063#c15

**Comment by pypingou** [comment]
So anitya announces the tag as ``v1.3.3``, the-new-hotness ignores it to do version comparison but then uses it to get the new sources.

Question becomes: how can we know when to include and when to exclude it?

**Comment by voxik** [comment]
> So anitya announces the tag as v1.3.3

But where the **v** comes from? Anytia should be querying this url:

http://rubygems.org/api/v1/versions/fog-sakuracloud/latest.json

And there is no **v** and neither there will be.

**Comment by pypingou** [comment]
It's coming from github: https://release-monitoring.org/project/5820/

**Comment by voxik** [comment]
Ah, there is GH backend in use? How that happened?

**Comment by pypingou** [comment]
Apparently it got set-up automatically upon imports and I edited it to GitHub likely because the former backend didn't work

**Comment by pypingou** [comment]
Ok it's fixed in anitya and seems to be working fine now.

Thanks for the notifying!

**Comment by voxik** [comment]
Wondering how many other rubygem- packages using non RubyGems backend are there ....

**Comment by pypingou** [comment]
This could be scripted :)

**Comment by voxik** [comment]
Definitely. Thank you for taking care about it :smirk:

**Comment by pypingou** [comment]
Sure thing, anytime :)
