### ISSUE TITLE
no notification on bugzilla that real build is completed

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/the-new-hotness#74]
I just completed [build](http://koji.fedoraproject.org/koji/buildinfo?buildID=688869) in rawhide for [new release bug] (https://bugzilla.redhat.com/show_bug.cgi?id=1267778) but then no comment on bugzilla that real build is completed on koji.

**Comment by ralphbean** [comment]
Should be fixed by #71.  I'll push out a release of that today.
