### ISSUE TITLE
koji scratch build notifications

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/the-new-hotness#77]
Why the-new-hotness want to comment on new package review bugzilla for every further attempt of fixing the package?
e.g. I am trying to fix test failure and tried to check if everything builds fine on koji but all such attempts are commented on https://bugzilla.redhat.com/show_bug.cgi?id=1265321

Its unnecessary notification to bugzilla CC members as well.

**Comment by ralphbean** [comment]
Agreed.  It should only do it once (and only when the build succeeds).

**Comment by ralphbean** [comment]
I believe this is fixed now.  It should only comment on the bug once when the build succeeds.
