### ISSUE TITLE
Problem with reading yum-config

### ISSUE THREAD

**Issue by phracek** [fedora-infra/the-new-hotness#80]
I try to run fedmsg-hub on y testing machine based on your README.mb
but unfortunately when topic version.update arise then fedmsg-hub fails with message like
~~~
(my-env)[root@rebase-helper-upstream-monitoring bin]# ./fedmsg-hub > fedmsg-hub.txt
Config error: Can not read configuration: /root/my-env/bin/./yum-config
~~~

Where shall I store yum-config?
What does it come from?

Did I configure fedmsg-hub wrongly?
I have applied PR https://github.com/fedora-infra/the-new-hotness/pull/79

Any help would be welcome.

**Comment by ralphbean** [comment]
Yes!  The instructions assume that you are running it with `cwd` in the root of the git repo.  ``yum-config`` is there, and also a ``fedmsg.d/`` directory is there (which has some default configuration).

Edit ``fedmsg.d/hotness-example.py`` and fill in some of the blank values (like a username/password for partner-bugzilla.redhat.com and a FAS username/password for release-monitoring.org).

Then, with ``my-env`` activated, run fedmsg-hub from the git checkout dir

```bash
(my-env)[root@rebase-helper-upstream-monitoring the-new-hotness]# pwd
/root/the-new-hotness
(my-env)[root@rebase-helper-upstream-monitoring the-new-hotness]# fedmsg-hub > fedmsg-hub.txt
```

**Comment by ralphbean** [comment]
I'd note that fedmsg looks in ``/etc/fedmsg.d/`` and ``cwd`` to find its config.  So, on production systems, we usually just rely on ``/etc/fedmsg.d/``, but for development it matters which directory you are in when you execute a command.

**Comment by phracek** [comment]
I guess, that it is not a bug. Closing it.
