### ISSUE TITLE
hotness is failing to map new nodejs packages with npm repository as upstream

### ISSUE THREAD

**Issue by pnemade** [fedora-infra/the-new-hotness#89]
See https://apps.fedoraproject.org/datagrepper/raw?topic=org.fedoraproject.prod.hotness.project.map

**Comment by ralphbean** [comment]
Ah, I think I see.  In our [anitya module](https://github.com/fedora-infra/the-new-hotness/blob/develop/hotness/anitya.py#L25) there is code to handle ``npmjs.org`` but not ``npmjs.com``.
