### ISSUE TITLE
f24 build is notified in f23 ticket

### ISSUE THREAD

**Issue by voxik** [fedora-infra/the-new-hotness#97]
Recently, I received this notification:

```
vondruch's real build of rubygem-will_paginate-3.1.0-1.fc24 for RHBZ#1239978 completed
    https://bugzilla.redhat.com/show_bug.cgi?id=1239978
```

But if you'll check the ticket it is F23 (it used to be Rawhide bug few months ago) bug, so the build should not be referenced there IMO.

IOW, the "Version" field in BZ should be probably taken into account.

BTW this was originally reported at https://github.com/fedora-infra/fmn/issues/112

**Comment by Zlopez** [comment]
This issue is too old, so I'm closing this ticket. Feel free to reopen it.
